name: Read Test File on Update
# Trigger the workflow on push to the main branch
on:
 push:
  branches:
   - main
  paths:
   - 'myfile.py' # Specify the path to the text file
jobs:
 read-file:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout code
     uses: actions/checkout@v3
   - name: Read the pyhton file
     run: |
      cat myfile.py
